### ISSUE TITLE
AGP library plugin requirement

### ISSUE THREAD

**Issue by ming13** [cashapp/paparazzi#105]
The current version of the `PaparazziPlugin` requires to have `com.android.library` declared. Is it intentional? I’m asking because I’ve tried to use it with a usual application module and saw the plugin complaint.

```
The Android Gradle library plugin must be applied before the Paparazzi plugin.
```

**Comment by jrodbx** [comment]
That is correct.  This is because the merged resources for library modules are in xml, while for application modules, they are transformed to a binary flat format, which Paparazzi is currently unable to parse.

In a future release, we hope to be able to support app modules.  Workaround for now would be to move the layout resources or custom views into a separate library module and apply the plugin in that module.
