### ISSUE TITLE
Content Descriptions for custom buttons are not reported in Accessibility test

### ISSUE THREAD

**Issue by alexabenedict** [cashapp/paparazzi#1095]
**Description**

The content descriptions for custom button views are not getting reported in the accessibility snapshots.

**Expected behavior**
Each button should be highlighted in the snapshot with a corresponding content description, i.e. "1 button", "2 button"... and so on.

**Additional information:**
Paparazzi Version: 1.3.2
Compile SDK: 33
Gradle Version: 8.x
Android Gradle Plugin Version: 8.x

**Comment by jrodbx** [comment]
@geoff-powell @adamalyyan would you mind taking a look?

**Comment by adamalyyan** [comment]
I can take a look at this

**Comment by adamalyyan** [comment]
Took a look and this is happening since the AccessibilityRenderExtension in Paparazzi looks for whether `isImportantForAccessibility` is set and the `View` has a non-null `contentDescription`. In the case of the Keypad, the buttons didn't have a `contentDescription` set on the `View` for the button, but instead only had it set on the `AccessibilityNodeInfoCompat` which gets used by TalkBack to walk the hierarchy. The fix here was to set the `contentDescription` on the button view (done in the attached PR).

**Comment by jrodbx** [comment]
Closing as developer error
