### ISSUE TITLE
Use Skia Renderer

### ISSUE THREAD

**Issue by gpeal** [cashapp/paparazzi#110]
Android Studio 4.0 switched to Skia for its layout rendering (from java2d) which means it should support more rendering features. I think it's missing some things like PathMeasure.getSegment if I remember correctly.

If Paparazzi is able to use skia, I would consider switching the Lottie regression tests to it.

**Comment by saket** [comment]
Continuing my conversation from #127: the new layoutlib also brings [fixes for text rendering](https://issuetracker.google.com/issues/153831966) when spans are involved.

**Comment by ekimmel-ta** [comment]
Hello, I've started looking into updating layoutlib to 4.1.1 and I've hit a snag.  As of 4.0, the data directory organization inside layoutlib has changed and no longer matches the structure of the Android SDK.  Specifically, the system font files are contained with a `native` and `standard` folder inside of fonts. https://android.googlesource.com/platform/prebuilts/studio/layoutlib/+/refs/tags/studio-4.1.1/data/fonts/standard/

This is resulting in any/all inflations falling due to this missing file and android.graphics.Typeface being unable to load. I'm not familiar with overriding resource paths to know how to direct layoutlib to its internal data directory rather than the android SDKs, if that's even a viable option.

**Comment by jrodbx** [comment]
Fixed in https://github.com/cashapp/paparazzi/pull/251
