### ISSUE TITLE
Support for coroutines/produceState

### ISSUE THREAD

**Issue by AlexanderGH** [cashapp/paparazzi#1166]
**Description**
Some of the other issues make it seems like coroutines inside composables should work with Paparazzi, but for some reason they do not in the below repro case.

**Steps to Reproduce**
The following shows ProduceState Does Not Work

```

import androidx.compose.material.Text
import androidx.compose.runtime.produceStateimport app.cash.paparazzi.DeviceConfig
import app.cash.paparazzi.Paparazzi
import kotlinx.coroutines.time.delay
import java.time.Duration
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith
import com.google.testing.junit.testparameterinjector.TestParameterInjector

@RunWith(TestParameterInjector::class)
class MyTest {

    @get:Rule
    val paparazzi = Paparazzi(
        deviceConfig = DeviceConfig.PIXEL_6_PRO.copy(softButtons = false),
        maxPercentDifference = 0.01,
    )

    @Test
    fun foobar() {
        paparazzi.snapshot {
            val text = produceState("ProduceState Does Not Work", "") {
                value = testSuspendFunction()
            }
            Text(text = text.value)
        }
    }

    suspend fun testSuspendFunction(): String {
        delay(Duration.ofMillis(1)) // or anything that prevents the compiler from turning this into a regular non-suspend function
        return "ProduceState Works"
    }
}
```

**Expected behavior**
The above code should render ProduceState Works

**Additional information:**
- Paparazzi Version: 1.3.1
- OS:
- Compile SDK: 
- Gradle Version: 8.5
- Android Gradle Plugin Version: 8.1.3

**Screenshots**

**Comment by gamepro65** [comment]
produceState uses a `CoroutineContext` whose `CoroutineDispatcher` is backed by a main `Handler`. What this means is when you run an actual suspending fun you need to wait for the result of the suspend call to be delivered back to main. The problem is we are already in the process of capturing the current frame so your coroutine result isn't available in time for the first frame rather queued up for the second frame. This mimics what happens on real devices in that the code above will not show "ProduceState Works" in time for the first frame and will flicker in. 

To get the above working you would either need to seed a `CoroutineContext` which uses `Dispatchers.Unconfined` to force synchronous suspends or use the experimental Paparazzi#gif API which will capture the frame that the change gets applied in
![dfa88824a43e924cd578143542e5d3fc89b052c3](https://github.com/cashapp/paparazzi/assets/672316/6c44b5d4-8fc7-412e-98db-70450c0566e9)

**Comment by AlexanderGH** [comment]
Thanks. I did try using .gif() before filing this issue, but for some reason i wasn't able to see that flickering animation you have above (though the code in the issue is also much simpler than what I actually was testing .gif() with, though threading-wise it was equivelenent). I'll look into the feasibility of overriding the coroutine dispatcher.

Ideally paparazzi could somehow do the overriding automatically or provide some easy way to enable it, but I would totally get if it's considered out of scope of the project, so feel free to close this if there's nothing that makes sense to improve in paparazzi for this case.

**Comment by gamepro65** [comment]
Gonna close for now since it seems to be working as intended. Feel free to open a new issue if you continue running into trouble or have a different reproduction case to work though.
