### ISSUE TITLE
Add support for test filtering to Gradle tasks

### ISSUE THREAD

**Issue by Egorand** [cashapp/paparazzi#181]
As test suites grow, it would be handy to be able to pass filtering arguments to Paparazzi tasks, similar to Gradle's built-in test tasks (see [Test filtering](https://docs.gradle.org/current/userguide/java_testing.html#test_filtering)):

```
./gradlew views:recordPaparazziDebug --tests FooView
```

**Comment by Egorand** [comment]
Haven't looked at the Gradle plugin implementation, but I wonder if this can be achieved by simply inheriting from the right Gradle task types, smth like `Test`. Will take a closer look.

**Comment by jrodbx** [comment]
Looked into this, 

`--tests` is parsed by [CommandLineTaskParser](https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/execution/commandline/CommandLineTaskParser.java) and used to set AbstractTestTask#filter via [AbstractTestTask#setTestNameIncludePatterns](https://github.com/gradle/gradle/blob/master/subprojects/testing-base/src/main/java/org/gradle/api/tasks/testing/AbstractTestTask.java#L569).

Rather than rewriting the parsing logic myself, I tried cheating and making the "record" and "verify" tasks inherit from Task.class so as to automatically the "--tests" option and then relay them over to the actual "test" task (similar to how test system properties are set), but I kept getting NPEs due to eager task realization.  I'm prob missing something, so will take another look for next release.
