### ISSUE TITLE
Screenshot unable to capture android material components

### ISSUE THREAD

**Issue by w2ji** [cashapp/paparazzi#219]
When trying to take a screenshot of any com.google.android.material.* components, it would just show the class name and not the actual component. See attached image I tested in the sample app:

![image](https://user-images.githubusercontent.com/4450035/111877626-61c3ff80-8961-11eb-9698-32e95f2edf0b.png)

**Comment by jrodbx** [comment]
Do you have repro steps, perhaps a branch I can take a look at?

**Comment by w2ji** [comment]
Hi @jrodbx 
I don't have access to push branch up to this. But how I reproduced was:
1. import android material library in gradle:   
`implementation "com.google.android.material:material:1.3.0"` 
2. Adding 
`  <com.google.android.material.button.MaterialButton
      android:layout_width="match_parent"
      android:layout_height="wrap_content"
      android:text="Material Button"
      />`

To keypad.xml and run the sample screenshot test.

**Comment by w2ji** [comment]
@jrodbx If you have any idea why this is happening or anything I can help to resolve this. I am happy to help.

**Comment by jrodbx** [comment]
Repro'd the problem following the steps above:

Some background: Paparazzi relies on LayoutLib, which tends to only mock out Android platform code execution.

Taking a quick look at Material Button, the primary constructor looks like this:
```
  public MaterialButton(@NonNull Context context, @Nullable AttributeSet attrs, int defStyleAttr) {
    ...

    TypedArray attributes =
        ThemeEnforcement.obtainStyledAttributes(
            context, attrs, R.styleable.MaterialButton, defStyleAttr, DEF_STYLE_RES);
    ...
  }
```

which calls:
```
  @NonNull
  public static TypedArray obtainStyledAttributes(...) {

    // First, check for a compatible theme.
    checkCompatibleTheme(context, set, defStyleAttr, defStyleRes);
    
    ...
  }
```
which calls:
```
  private static void checkCompatibleTheme(...) {
    TypedArray a =
        context.obtainStyledAttributes(
            set, R.styleable.ThemeEnforcement, defStyleAttr, defStyleRes);
    boolean enforceMaterialTheme =
        a.getBoolean(R.styleable.ThemeEnforcement_enforceMaterialTheme, false);
    a.recycle();

    if (enforceMaterialTheme) {
      ...
      checkMaterialTheme(context);
    }
    ...
  }
```
which calls:
```
  public static void checkMaterialTheme(@NonNull Context context) {
    checkTheme(context, MATERIAL_CHECK_ATTRS, MATERIAL_THEME_NAME);
  }

  ...

  private static void checkTheme(
      @NonNull Context context, @NonNull int[] themeAttributes, String themeName) {
    if (!isTheme(context, themeAttributes)) {
      throw new IllegalArgumentException(
          "The style on this component requires your app theme to be "
              + themeName
              + " (or a descendant).");
    }
  }
```

Then, reviewing the Paparazzi Junit test report (open `file://PAPARAZZI_ROOT/sample/build/reports/tests/testDebugUnitTest/classes/app.cash.paparazzi.sample.KeypadViewTest.html`) and clicking "Standard Error" shows:
```
Caused by: java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.MaterialComponents (or a descendant).
	at com.google.android.material.internal.ThemeEnforcement.checkTheme(ThemeEnforcement.java:243)
	at com.google.android.material.internal.ThemeEnforcement.checkMaterialTheme(ThemeEnforcement.java:217)
	at com.google.android.material.internal.ThemeEnforcement.checkCompatibleTheme(ThemeEnforcement.java:145)
	at com.google.android.material.internal.ThemeEnforcement.obtainStyledAttributes(ThemeEnforcement.java:76)
	at com.google.android.material.button.MaterialButton.<init>(MaterialButton.java:229)
	at com.google.android.material.button.MaterialButton.<init>(MaterialButton.java:220)
	... 69 more
```


Solution: add the theme to your Paparazzi rule, like so:
```
 @get:Rule
  var paparazzi = Paparazzi(
    theme = "Theme.MaterialComponents"
  )
```
and re-run to go from:
![Screen Shot 2021-03-24 at 7 12 28 PM](https://user-images.githubusercontent.com/1868149/112395542-fbc6d780-8cd4-11eb-88a4-1f92bd12548f.png)

to:
![Screen Shot 2021-03-24 at 7 12 45 PM](https://user-images.githubusercontent.com/1868149/112395557-01bcb880-8cd5-11eb-8db7-f4f6a5bf26c9.png)


Closing this issue, but this investigation surfaces more actions to improve the developer experience:
1) Internally-thrown exceptions should be surfaced more easily.  Similar to https://github.com/cashapp/paparazzi/issues/215.
2) Document Paparazzi's configuration better to show that theming is an option.
3) Provide support for auto-detecting and wiring [MaterialComponentsViewInflater](https://developer.android.com/reference/com/google/android/material/theme/MaterialComponentsViewInflater).  Similar to how [AppCompat support is enabled here](https://github.com/cashapp/paparazzi/blob/master/paparazzi/src/main/java/app/cash/paparazzi/Paparazzi.kt#L351).  

Otherwise, xml layouts must explicitly declare the FQCN of any MaterialComponents widgets, i.e.,:
```
<com.google.android.material.button.MaterialButton
      android:layout_width="match_parent"
      android:layout_height="wrap_content"
      android:text="Material Button"
      />
```

instead of:
```
<Button
      android:layout_width="match_parent"
      android:layout_height="wrap_content"
      android:text="Material Button"
      />
```
and automagically inflating the correct MaterialComponents equivalent.

**Comment by jrodbx** [comment]
Added https://github.com/cashapp/paparazzi/issues/222 for 1)

**Comment by jrodbx** [comment]
2) handled by https://github.com/cashapp/paparazzi/issues/117

**Comment by jrodbx** [comment]
3. is now covered here: https://github.com/cashapp/paparazzi/issues/223

**Comment by w2ji** [comment]
Thank you so much for the detailed comments! Will test this out!
