### ISSUE TITLE
Running paparazzi tests from the IDE deletes snapshot folder

### ISSUE THREAD

**Issue by ncipollo** [cashapp/paparazzi#280]
It looks like the snapshots directory gets removed whenever I run the paparazzi tests from the IDE. I think this is because the IDE will first execute the clean task for your test flavor. For example:

> Task :sample:cleanTestDebugUnitTest

This task appears to delete the snapshots folder (the same thing happens if I run it directly via gradle). I'm not 100% positive but I think this is happening because of the following line in the plugin: https://github.com/cashapp/paparazzi/blob/9f7ebabed499545da798171f101e40135b38d27b/paparazzi-gradle-plugin/src/main/java/app/cash/paparazzi/gradle/PaparazziPlugin.kt#L115

I suspect that gradle will end up cleaning this folder because it sees it as an output folder.

**Comment by jrodbx** [comment]
You're correct about the test task outputs setup.  Unfortunately, the problem lies with Android Studio's run configuration automatically prepending the cleanTestDebugUnitTest in the task list, as you pointed out.

<img width="1060" alt="Screen Shot 2021-11-20 at 12 46 30 AM" src="https://user-images.githubusercontent.com/1868149/142715975-79a6cb0f-febd-4f7d-ba20-cd3c9303ed58.png">

Luckily, it looks like Android Studio Chipmunk Canary 5 fixes this!  See https://issuetracker.google.com/issues/194989584.

<img width="1040" alt="Screen Shot 2021-11-20 at 12 54 18 AM" src="https://user-images.githubusercontent.com/1868149/142716166-c028393c-46db-43ea-9701-815d2922e264.png">

Closing as wont fix, since it's an Android Studio bug/issue.
