### ISSUE TITLE
Feature Request: Enable Testing Modules with main source sets

### ISSUE THREAD

**Issue by agrosner** [cashapp/paparazzi#561]
Hey 👋 , I am looking to use paparazzi at my company and I want to bundle a common testing library using Paparazzi device 
profiles:
```kotlin
val phone = Paparazzi(
        deviceConfig = DeviceConfig.PIXEL_5.copy(softButtons = false, screenHeight = 1),
        theme = "AppTheme.Base",
        renderingMode = SessionParams.RenderingMode.V_SCROLL
    )

    val tablet = Paparazzi(
        deviceConfig = DeviceConfig.PIXEL_C.copy(softButtons = false, screenHeight = 1),
        theme = "AppTheme.Base",
        renderingMode = SessionParams.RenderingMode.V_SCROLL
    )
```

This library is a testing library so its sources live in `main`. but Paparazzi only applies the dependencies to test configurations. 
So I have to add the dependencies manually:
```kotlin
  val operatingSystem = DefaultNativePlatform.getCurrentOperatingSystem()
    val nativeLibraryArtifactId = when {
        operatingSystem.isMacOsX -> {
            val osArch = System.getProperty("os.arch").toLowerCaseAsciiOnly()
            if (osArch.startsWith("x86")) "macosx" else "macarm"
        }
        operatingSystem.isWindows -> "win"
        else -> "linux"
    }
    val layoutLibVersion = "2021.2.1-patch1-fa3aa65"

    implementation(dependencyNotation = "app.cash.paparazzi:paparazzi:1.0.0")
    implementation(dependencyNotation = "app.cash.paparazzi:layoutlib-native-$nativeLibraryArtifactId:$layoutLibVersion")

```

Is there a way to pass in a configuration option to enable setting the dependencies on `main` source set? We do not want to store snapshots in the module, rather supply common primitives using the paparazzi API.

**Comment by TWiStErRob** [comment]
I got really curious about this, why is this a problem? What is not working? In general it's expected needing to add dependencies to libraries manually (adding deps via Gradle Plugins is the exception, not the general case). You don't need to even apply Paparazzi Gradle Plugin to this module, it's just a standard JVM module. I have a similar shared library within my project and it all works fine: https://github.com/TWiStErRob/net.twisterrob.sun/blob/43037400f095c0c247c02c7964214a01666ade56/component/paparazzi/src/main/java/net/twisterrob/sun/test/screenshots/PaparazziFactory.kt (see also [build.gradle](https://github.com/TWiStErRob/net.twisterrob.sun/blob/master/component/paparazzi/build.gradle.kts))

Note that you don't need layoutlib native dependencies to create these utility classes, because you are not going to use this library in any other context than in Paparazzi JVM tests in other projects. Those projects/modules will set up the Paparazzi classpath as expected because they have to apply the plugin. So the native deps will exist at runtime when needed.

For testing you again have to set up a fully functional Paparazzi module, so even there everything is given and main source set doesn't play.

**Comment by j-roskopf** [comment]
I was able to get my setup working following a similar setup as above. Thanks for the tip!

**Comment by jrodbx** [comment]
Closing, as @TWiStErRob 's explanation sums it up.  If you want to bundle Paparazzi in a testing lib, you will need to set up those dependencies manually, as the Gradle plugin expects direct testing.
