### ISSUE TITLE
No screenshot generated

### ISSUE THREAD

**Issue by timrijckaert** [cashapp/paparazzi#612]
**Description**
Hello

I noticed that there is some missing information in the README to setup Paparazzi.

When I don't apply the `id("org.jetbrains.kotlin.android")` plugin the build does not fail, but simply does not generate any screenshot as stated also in following comment.
https://github.com/cashapp/paparazzi/issues/449#issuecomment-1146851253

I tripped over this again when setting up in a new project.

Would be an idea to add this explicitly in the README?

**Additional information:**
- Paparazzi Version: 1.0.0 and 1.1.0
- OS: Mac
- Compile SDK:  31
- Gradle Version:  7.4.2
- Android Gradle Plugin Version:  7.2.2

**Comment by alexjlockwood** [comment]
I ran into this issue as well. Agree this should be added to the README as it took me a while to figure out why snapshots were not being generated.

**Comment by jrodbx** [comment]
Unless I'm missing something, based on the description in https://github.com/cashapp/paparazzi/issues/449#issuecomment-1146851253, this is a Compose issue not a Paparazzi issue, since Paparazzi should work in a pure Java Android project with legacy views just fine.  Perhaps file an issue with the Compose team?
