### ISSUE TITLE
Using `pluralStringResource` for a Paparazzi test only ever renders the first item in the plurals array

### ISSUE THREAD

**Issue by weverb2** [cashapp/paparazzi#634]
**Description**
When rendering a label in Jetpack Compose using the `pluralStringResource` the first array entry in the `plurals` resource is always used.

**Steps to Reproduce**
1. Create a label that uses `pluralStringResource` to show a plural string
2. Render that label in a paparazzi snapshot with multiple different values passed in for `count`
3. Observe that the recorded screenshot only ever uses the first entry in the plurals array

**Expected behavior**
The rendering should reflect the value passed into count for `pluralStringResource`

**Additional information:**
- Paparazzi Version: 1.0.0
- OS: MacOS Monterey 12.6.1
- Compile SDK: 32
- Gradle Version: 7.5
- Android Gradle Plugin Version: 7.2.2

**Comment by jrodbx** [comment]
Directly relates to https://github.com/cashapp/paparazzi/issues/524, since the deprecated [ValueResourceParser.startElement](https://cs.android.com/android/platform/superproject/+/master:frameworks/layoutlib/bridge/tests/src/com/android/ide/common/resources/deprecated/ValueResourceParser.java;l=122?q=ValueResourceParser) does not handle plural resources properly.

**Comment by jrodbx** [comment]
This is fixed on master when enabling the new resource loading mechanism, tracked in #524.
