### ISSUE TITLE
Unable to run the recordPaparazziDebug command, failing with Missing platform version 33

### ISSUE THREAD

**Issue by hellosagar** [cashapp/paparazzi#643]
**Description**
Trying to record the screenshots, but it's failing with this error 
```
Missing platform version 33. Install with SDK manager --install "platforms;android-33"
```

Tho, I've all the platforms installed.
<img width="730" alt="Screenshot 2022-12-04 at 7 22 46 PM" src="https://user-images.githubusercontent.com/50016799/205494484-772a53a3-175e-45b9-af1d-bad0f3196534.png">

**Steps to Reproduce**
I've run this command, to generate the screenshots
```
./gradlew module:recordPaparazziDebug --tests "*Screenshot" -Pscreenshot
```

**Expected behavior**
It should've generated the screenshots instead of giving the error

**Additional information:**
- Paparazzi Version: 1.2.0
- OS: macOS (13.0.1 (22A400))
- Compile SDK: 33
- Gradle Version: 7.6
- Android Gradle Plugin Version: 7.3.0

**Screenshots**
Screenshot of error
<img width="1149" alt="Screenshot 2022-12-04 at 7 27 33 PM" src="https://user-images.githubusercontent.com/50016799/205494706-df33603b-636e-41cd-9d24-1a8ae22fa72e.png">

**Comment by hellosagar** [comment]
but as I've mentioned above in the screenshot from android studio. I've platform-33 intalled

**Comment by TWiStErRob** [comment]
The directory that is checked is resolved here:

https://github.com/cashapp/paparazzi/blob/07cefe8fb380d07af581761ab4dac32fbc310e8a/paparazzi/paparazzi/src/main/java/app/cash/paparazzi/Environment.kt#L58-L59

Double-check that your system is set up to run Paparazzi (you might be missing [standard Android SDK env vars](https://developer.android.com/studio/command-line/variables#envar)):

https://github.com/cashapp/paparazzi/blob/07cefe8fb380d07af581761ab4dac32fbc310e8a/paparazzi/paparazzi/src/main/java/app/cash/paparazzi/Environment.kt#L46-L48

---

@jrodbx there are at least two things that could be done here to improve things (happy to raise a PR):
 * feels like since the "root" one is deprecated, the new variable should be checked first or validated as [documented](https://developer.android.com/studio/command-line/variables#envar) and [implemented](https://cs.android.com/android-studio/platform/tools/base/+/mirror-goog-studio-main:build-system/gradle-core/src/main/java/com/android/build/gradle/internal/SdkLocator.kt;l=138-165?q=getSdkPathProperty).
 * output the SDK folder (`platformDirPath.subpath(0, elements - 1)`) in this error message to remove guessing:
   (there might be multiple SDKs installed, or the env vars pointing to the wrong place):
 https://github.com/cashapp/paparazzi/blob/07cefe8fb380d07af581761ab4dac32fbc310e8a/paparazzi/paparazzi/src/main/java/app/cash/paparazzi/Environment.kt#L40

---

@hellosagar to verify if I'm right with these guesses, can you please:
 * Put a breakpoint on one of the lines mentioned above in `Environment.kt`
 * Run
    ```shell
    ./gradlew module:recordPaparazziDebug --tests "*Screenshot" -Pscreenshot --debug-jvm
    ```
 * Attach a Remote debugger to Gradle tests to see the values  
![image](https://user-images.githubusercontent.com/2906988/205619360-b02130a8-41c8-4030-a6b8-fd0c36875df3.png)  
You might need to select a module for classpath to resolve the breakpoint.

**Comment by jrodbx** [comment]
> but as I've mentioned above in the screenshot from android studio. I've platform-33 intalled

Oops, I missed that detail in your screenshot.  Sorry!

**Comment by shanio** [comment]
Hey, had this issue as well and was able to make it work by removing own definition of ANDROID_HOME env. variable in shell profile.

**Comment by hellosagar** [comment]
Thanks a lot of the support, I debugging the code as suggested and I found that I've some weired `"` in my ANDROID_HOME which I copied from the slack.

Thankfully now Its solved. 

Just my personal suggestion, isnt its a good idea to print the bad path which is causing the error so that user is aware about it more.

**Comment by Burtan** [comment]
Paparazzi seems to ignore the local.properties file with sdk.dir property. So when your project relies on this file to detect the android-sdk, paparazzi won't detect it.

**Comment by romans-boi** [comment]
Just ran into the same problem - found the issue was that the path I had for `$ANDROID_HOME` was not absolute, so it was `~/Library/Android/sdk` instead of `/Users/<user>/Library/Android/sdk`.
