### ISSUE TITLE
The Android Gradle library plugin must be applied for Paparazzi to work properly

### ISSUE THREAD

**Issue by noloman** [cashapp/paparazzi#672]
**Description**
I'm getting the following error when following the instructions in order to set up Paparazzi:
`The Android Gradle library plugin must be applied for Paparazzi to work properly.`

**Steps to Reproduce**
Add `id 'app.cash.paparazzi' version '1.1.0'` to the `plugins` section of the root `build.gradle` file

**Expected behavior**
It should install I guess

**Additional information:**
- Paparazzi Version: 1.1.0
- OS: macOS 12.6.1 Monterrey
- Compile SDK: 33
- Gradle Version: 7.4.2
- Android Gradle Plugin Version: 7.3.1

**Comment by TWiStErRob** [comment]
If you don't have the Android plugin applied, what do you expect to test? There's no Android code the to verify. Also there are problems if Paparazzi wants to auto-pick:
* What kind of module is it? There are libs, test, feature, app, ... these are all different plugins in the AGP artifact and YOU have to choose which.
* Which version to apply from what repository?

Plugins in Gradle world are independent usually, but they can work together based on a presence of another plugin. In this case there's is a dependency, but it cannot be transitively applied. You would apply Paparazzi (a testing plugin) on top of your existing Android setup. Just as you would with Google Play Services, Firebase, Crashlytics. Notice how these are also Android related, but they can't pick AGP for you either.

---

Since you're applying to the root, that might not be an Android module as described above. Paparazzi needs something to build on to create testing tasks specific for that module, same as AGP.

What you would usually do is `id 'app.cash.paparazzi' version '1.1.0' apply false` in the root build.gradle and in each module where you need it: `id 'app.cash.paparazzi'` (i.e. without the `version` or `apply` clauses)

**Comment by jrodbx** [comment]
Closing as resolved, per @TWiStErRob 's response.
