### ISSUE TITLE
Could not find app.cash.paparazzi:paparazzi-gradle-plugin:1.0.0-square08.

### ISSUE THREAD

**Issue by jaredsburrows** [cashapp/paparazzi#88]
## Repro:
git clone https://github.com/cashapp/paparazzi
cd paparazzi
gradlew tasks

## Error:
```
$ gradlew tasks
Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'paparazzi-parent'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find app.cash.paparazzi:paparazzi-gradle-plugin:1.0.0-square08.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/app/cash/paparazzi/paparazzi-gradle-plugin/1.0.0-square08/paparazzi-gradle-plugin-1.0.0-square08.pom
       - https://dl.google.com/dl/android/maven2/app/cash/paparazzi/paparazzi-gradle-plugin/1.0.0-square08/paparazzi-gradle-plugin-1.0.0-square08.jar
       - https://repo.maven.apache.org/maven2/app/cash/paparazzi/paparazzi-gradle-plugin/1.0.0-square08/paparazzi-gradle-plugin-1.0.0-square08.pom
       - https://repo.maven.apache.org/maven2/app/cash/paparazzi/paparazzi-gradle-plugin/1.0.0-square08/paparazzi-gradle-plugin-1.0.0-square08.jar
       - https://jcenter.bintray.com/app/cash/paparazzi/paparazzi-gradle-plugin/1.0.0-square08/paparazzi-gradle-plugin-1.0.0-square08.pom
       - https://jcenter.bintray.com/app/cash/paparazzi/paparazzi-gradle-plugin/1.0.0-square08/paparazzi-gradle-plugin-1.0.0-square08.jar
       - file:/Users/<>/.m2/repository/app/cash/paparazzi/paparazzi-gradle-plugin/1.0.0-square08/paparazzi-gradle-plugin-1.0.0-square08.pom
       - file:/Users/<>/.m2/repository/app/cash/paparazzi/paparazzi-gradle-plugin/1.0.0-square08/paparazzi-gradle-plugin-1.0.0-square08.jar
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
```

**Comment by jrodbx** [comment]
The project has not yet been released for public consumption.  Workaround would be to modify the build scripts for the time being.

**Comment by jaredsburrows** [comment]
Ok. This was not mentioned in the README.md or project site. What would be the work around?

**Comment by mitchware-cfa** [comment]
@jaredsburrows It would appear that the Gradle files need to be modified to not fetch `paparazzi-gradle-plugin` remotely and instead assemble it locally and provide it as a local dependency to the other module. I'll let you know if I can find a way to do that

**Comment by jrodbx** [comment]
workaround steps are:
1) disable sample from settings.gradle, since it depends on a released plugin
2) remove plugin reference from buildscript.repositories block
3) install locally
4) optionally undo 1-2 pointing to locally installed version, updating repositories blocks appropriately

**Comment by mitchware-cfa** [comment]
Thanks so much @jrodbx! Looking forward to checking out your work here :)

**Comment by mitchware-cfa** [comment]
I've attempted to get this working by building locally, but I'm still hitting some roadblocks running the actual tests in the `sample` module. Here's a summary of what I've tried so far

- Remove the sample module from `settings.gradle` & classpath dependency on the plugin
- Attempt to build the lib & gradle plugin and publish it locally, through some combination of the following:
  - Had some issues with signing so I disabled that, though that doesn't seem directly related to my main issue here
  - Run `./gradlew libs:layoutlib:publishMavenJavaPublicationToMavenLocal`
  - Run `./gradlew :paparazzi-gradle-plugin:publishLocally`
  - Run `./gradlew :paparazz:publishLocally`
  - Manually assemble each and install to local maven via: 
    - ```
        mvn install:install-file \
            -Dfile=paparazzi/build/paparazzi-1.0.0-square07.jar \
            -DgroupId=app.cash.paparazzi \
            -DartifactId=paparazzi \
            -Dversion=1.0.0-square07 \
            -Dpackaging=jar`
        ```
    - ```
        mvn install:install-file \
            -Dfile=paparazzi-gradle-plugin/build/libs/paparazzi-gradle-plugin-1.0.0-square07.jar \
            -DgroupId=app.cash.paparazzi \
            -DartifactId=paparazzi-gradle-plugin \
            -Dversion=1.0.0-square07 \
            -Dpackaging=jar`
       ```
- Re-enable the plugin as a classpath dependency (though the name is defined as `square07` instead of `square08`) & re-declare the sample module in `settings.gradle`
  - At this point everything seems to assemble correctly, but the unit tests can't find the actual Paparazzi lib
- Manually add the main lib and JUnit4 as test-only dependencies within the sample module:
  - `testImplementation 'app.cash.paparazzi:paparazzi:1.0.0-square07'`
  - `testImplementation 'junit:junit:4.12'`

After that, running the actual sample tests that utilize Paparazzi don't run correctly and fail with the following error: `java.lang.NoClassDefFoundError: com/android/resources/ScreenOrientation` (when trying to initialize the default `DeviceConfig` instance).

At this point, its pretty clear that my locally-published artifacts are incorrect and didn't pull in the `layoutlib` dependency correctly. Running the `publishLocally` task worked fine for both the main module and gradle plugin module, but they didn't seem to actually _publish_ the artifact in my local repo (hence the manual `mvn install` command).

Not sure where to go from here - @jrodbx any ideas on what I missed? Apologies for bombarding you with messages today!

**Comment by martinbonnin** [comment]
If anyone's still interested, I have the sample working there: https://github.com/martinbonnin/paparazzi/tree/introduce-composite-build

It uses a composite build to substitute the `app.cash.paparazzi:paparazzi-gradle-plugin` dependency and gets the "app.cash.paparazzi:layoutlib" dependency from (maven snapshots](https://repo1.maven.org/maven2/app/cash/paparazzi/layoutlib/3.4.0/). 

You should be able to do:

```
./gradlew -p composite :sample:test
# screenshots should be in sample/build/reports/paparazzi/images/
```
