### ISSUE TITLE
Documentation web 404

### ISSUE THREAD

**Issue by rulogarcillan** [cashapp/paparazzi#961]
**Description**
api documentation gives 404 error

https://cashapp.github.io/paparazzi/1.x/paparazzi/app.cash.paparazzi/index.md

can you fix it?

Thanks

**Comment by TWiStErRob** [comment]
It was deleted by this commit: https://github.com/cashapp/paparazzi/commit/851de9ee9d7e841844b7935cd84a0a658b94202e

The parent of its originating commit is the restructure to single project, I think the problem is around here: https://github.com/cashapp/paparazzi/commit/59e545e54f2ed867c7d6e530526d1860781bd427#diff-91989431f997ac6f74ee5395a2023015687247a373b92adaccb5c964a0b7dcaeR12

**Comment by TWiStErRob** [comment]
I think this should fix it: https://github.com/cashapp/paparazzi/pull/962

**Comment by TWiStErRob** [comment]
@jrodbx this is not fixed yet because the `build` on master of https://github.com/cashapp/paparazzi/commit/58ede70a0e6dd978fdc725a0f3d5441765bb78d1 failed (strange unrelated errors) and that blocked `publish`.
