### ISSUE TITLE
Resources$NotFoundException when generating screenshots for sub-modules

### ISSUE THREAD

**Issue by apkelly** [cashapp/paparazzi#972]
**Description**
Our project has a sub-module for all our unit tests, this module depends on the feature modules in order to grab composables to test. When using paparazzi to render the screens, the android resources aren't discovered correctly. 

In the sample attached, there are 2 feature modules, with a simple composable that renders a string. When you run `./gradlew x-unit-tests:testDebug` you'll experience a `Resources$NotFoundException`. If you copy the string.xml files from within each feature module into the x-unit-tests module, then the screens are rendered correctly.

This exception is also seen when trying to reference Drawables....I assume it would be the case for any Android resource.

**Steps to Reproduce**
[PaparazziIssue.zip](https://github.com/cashapp/paparazzi/files/11929077/PaparazziIssue.zip)

**Expected behavior**
The resources for a given sub-module should be found when rendering a composable as part of a test, without needing to copy these into the test module itself.

**Additional information:**
- Paparazzi Version: 1.3.0
- OS: Mac
- Compile SDK: Java 17
- Gradle Version: 8.1
- Android Gradle Plugin Version: 8.0.2

**Screenshots**
n/a

**Comment by jrodbx** [comment]
thanks for the sample @apkelly!  it looks like the Gradle setup is the culprit here; when I change from:

```
    // Paparazzi UI testing.
    testImplementation(project(":feature1"))
    testImplementation(project(":feature2:ui"))
```

to

```
    // Paparazzi UI testing.
    implementation(project(":feature1"))
    implementation(project(":feature2:ui"))

```

the tests run as expected.

`testImplementation` will add the transitive modules to the `testRuntimeClasspath` where things like junit, truth, robolectric (i.e., jvm dependencies) typically live, where `implementation` or `api` will add them to the `runtimeClasspath` where android source sets tend to live.

can you confirm that this works on your actual project (i assume the sample was a minified version of your actual app)?

**Comment by apkelly** [comment]
Confirmed, switching to `implementation` from `testImplementation` fixes the resource loading issue!

Thanks.
