### ISSUE TITLE
Dialogs rendering differently between 1.3.0 and 1.3.1-SNAPSHOT

### ISSUE THREAD

**Issue by apkelly** [cashapp/paparazzi#991]
**Description**
When updating to the latest 1.3.1 SNAPSHOT release, my tests that contain dialogs all now have a empty space above the system ui navigation (see screenshot).

**Steps to Reproduce**
1. With Paparazzi 1.3.0, create a screenshot using Compose UI that renders a AlertDialog.
2. Update to Paparazzi 1.3.1-SNAPSHOT
3. Run verify.

**Expected behavior**
Screenshots should look the same.

**Additional information:**
- Paparazzi Version: 1.3.1-SNAPSHOT
- OS: Mac
- Compile SDK:
- Gradle Version:
- Android Gradle Plugin Version:

**Screenshots**
![Delta Example](https://github.com/cashapp/paparazzi/assets/2559953/b1306968-6987-44aa-86b6-89a6a1b56a56)

**Comment by apkelly** [comment]
Also, the default for `showSystemUi` seems to have changed from true to false, was this intentional?

**Comment by TWiStErRob** [comment]
Yes, https://github.com/cashapp/paparazzi/pull/932

**Comment by jrodbx** [comment]
@apkelly have a sample?  @adamalyyan isn't able to repro, so we wonder if this might have environment-specific configuration, like windows insets.

**Comment by apkelly** [comment]
Will get you one asap, just travelling in Spain.

**Comment by apkelly** [comment]
[PaparazziIssue.zip](https://github.com/cashapp/paparazzi/files/12092462/PaparazziIssue.zip)
![delta-com example paparazziissue ui paparazzi_IdleTests_feature1Snapshot](https://github.com/cashapp/paparazzi/assets/2559953/a6a856f5-cde0-4137-8c1c-2091fed02420)

Steps
1. In the .toml file set the paparazzi version to 1.3.0 and run `./gradlew x-unit-tests:recordPaparazziDebug`
2. In the .toml file change the paparazzi version to 1.3.1-SNAPSHOT and run `./gradlew x-unit-tests:verifyPaparazziDebug`
3. Note the output in the x-unit-tests/build/paparazzi/failures folder, it should match the attached image.

**Comment by adamalyyan** [comment]
Hi! We’ve dug into what is causing this and determined this is an expected change going forward in 1.3.1+. 

To give some background on what’s happening here: in 1.3.0 we made a slight change to how compose dialogs are added to the view hierarchy when taking a snapshot to better match what you see in an Android Studio preview, and fixing [this issue](https://github.com/cashapp/paparazzi/issues/769). As a result of this change, in 1.3.1, the parent view of the dialog is no longer the outer most view (which has a height of the full screen) but is attached to an inner layout which has a height of the full screen minus the height of any system UI (this can change depending on the theme, for example in your example, there is a nav bar and system bar so the height will the the full screen minus those). Since the height of the dialog’s parent is no longer the full screen height, the dialog gets centered in this smaller height view and the result is it’s in a slightly different position on the screen.

The reason for the empty space is that the themes background here is set to be white and when the dialog adds the gradient behind it, it only fills the dialog’s parent view which isn’t the full screen. You can see this behavior in Android Studio’s preview too. 

A suggestion would be to set `showsSystemUi` to be false (the default) or adjusting the theme passed into the Paparazzi test to use a dark background (this makes the bar at the bottom “disappear” since it blends in)

**Comment by adamalyyan** [comment]
Hey @hlandim, showSystemUi was changed to default to false in 1.3.0 onwards. If you want to enable it for your tests, you can set it when creating your Paparazzi instance:

`@get:Rule val paparazzi = Paparazzi(showSystemUi = true,)`

**Comment by hlandim** [comment]
> Hey @hlandim, showSystemUi was changed to default to false in 1.3.0 onwards. If you want to enable it for your tests, you can set it when creating your Paparazzi instance:
> 
> `@get:Rule val paparazzi = Paparazzi(showSystemUi = true,)`

Hey @adamalyyan, thanks for replying it.
Maybe I wasn't clear.
In fact, My issue is the opposite.
I don't want to show the system UI, but it is showing after updating to 1.3.0 version.
And I didn't change my code, witch always was 
```kotlin
@get:Rule val paparazzi = Paparazzi()
```

**Comment by adamalyyan** [comment]
Apologies, I misread your initial comment! Would you mind creating a separate issue for what you are seeing with an example and we can take a look.

**Comment by hlandim** [comment]
> Apologies, I misread your initial comment! Would you mind creating a separate issue for what you are seeing with an example and we can take a look.

Sure, I'll do as soon as possible

**Comment by hlandim** [comment]
Update: I just tried to create a new project using the latest version 1.3.1 and got the expected result, probably this is some dependencies cache from the other project, when a got a free time I'll try it again.
Thanks for the Help.
